# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: airframes_client_frame.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("airframes_client_frame.proto", :syntax => :proto3) do
    add_message "airframes.AcarsdecMessage" do
      optional :timestamp, :double, 1
      optional :station_id, :string, 2
      optional :channel, :uint32, 3
      optional :frequency, :double, 4
      optional :level, :sint32, 5
      optional :error, :uint32, 6
      optional :mode, :string, 7
      optional :label, :string, 8
      optional :block_id, :string, 9
      optional :ack, :string, 10
      optional :tail, :string, 11
      optional :flight, :string, 12
      optional :message_number, :string, 13
      optional :text, :string, 14
      optional :end, :bool, 15
    end
    add_message "airframes.Vdlm2decMessage" do
      optional :timestamp, :double, 1
      optional :station_id, :string, 2
      optional :channel, :uint32, 3
      optional :frequency, :double, 4
      optional :from_icao, :uint32, 5
      optional :to_icao, :uint32, 6
      optional :level, :sint32, 7
      optional :error, :uint32, 8
      optional :mode, :string, 9
      optional :label, :string, 10
      optional :block_id, :string, 11
      optional :ack, :string, 12
      optional :tail, :string, 13
      optional :flight, :string, 14
      optional :message_number, :string, 15
      optional :text, :string, 16
      optional :end, :bool, 17
      optional :departure_airport, :string, 18
      optional :destination_airport, :string, 19
      optional :arrival_eta, :string, 20
      optional :gate_out, :string, 21
      optional :ground_off, :string, 22
      optional :ground_on, :string, 23
      optional :gate_in, :string, 24
    end
    add_message "airframes.TestRequest" do
    end
    add_message "airframes.FrameRequest" do
    end
    add_message "airframes.AirframesClientFrame" do
      optional :source, :message, 1, "airframes.AirframesClientFrame.Source"
      optional :airframes, :message, 2, "airframes.AirframesClientFrame.AirframesConfig"
      oneof :message do
        optional :acarsdec_message, :message, 3, "airframes.AcarsdecMessage"
        optional :vdlm2dec_message, :message, 4, "airframes.Vdlm2decMessage"
      end
    end
    add_message "airframes.AirframesClientFrame.Source" do
      optional :app, :message, 1, "airframes.AirframesClientFrame.Source.App"
      optional :host, :message, 2, "airframes.AirframesClientFrame.Source.Host"
      optional :type, :enum, 3, "airframes.AirframesClientFrame.Source.SourceType"
      optional :format, :enum, 4, "airframes.AirframesClientFrame.Source.SourceFormat"
    end
    add_message "airframes.AirframesClientFrame.Source.App" do
      optional :type, :enum, 1, "airframes.AirframesClientFrame.Source.App.AppType"
      optional :version, :string, 2
    end
    add_enum "airframes.AirframesClientFrame.Source.App.AppType" do
      value :UNKNOWN_APP_TYPE, 0
      value :ACARSDEC, 1
      value :ACARSDECO2, 2
      value :VDLM2DEC, 3
      value :DUMPVDL2, 4
      value :JAERO, 5
      value :PC_HFDL, 6
      value :SORCERER, 7
    end
    add_message "airframes.AirframesClientFrame.Source.Host" do
      optional :platform, :enum, 1, "airframes.AirframesClientFrame.Source.Host.Platform"
      optional :os, :enum, 2, "airframes.AirframesClientFrame.Source.Host.OperatingSystem"
      optional :version, :string, 3
      optional :node_name, :string, 4
      optional :node_ip, :string, 5
    end
    add_enum "airframes.AirframesClientFrame.Source.Host.Platform" do
      value :UNKNOWN_PLATFORM, 0
      value :X86_32, 1
      value :X86_64, 2
      value :ARM_V6, 3
      value :ARM_V7, 4
      value :ARM_64, 5
    end
    add_enum "airframes.AirframesClientFrame.Source.Host.OperatingSystem" do
      value :UNKNOWN_OPERATING_SYSTEM, 0
      value :LINUX, 1
      value :MACOS, 2
      value :WINDOWS, 3
    end
    add_enum "airframes.AirframesClientFrame.Source.SourceType" do
      value :ACARS, 0
      value :VDL, 1
      value :HFDL, 2
      value :AERO, 3
    end
    add_enum "airframes.AirframesClientFrame.Source.SourceFormat" do
      value :HUMAN_READABLE_TEXT, 0
      value :BEAST, 1
      value :SBS3, 2
      value :PLANE_PLOTTER, 3
      value :JSON_GENERIC, 4
      value :JSON_ACARSDEC, 5
      value :JSON_VDLM2DEC, 6
    end
    add_message "airframes.AirframesClientFrame.AirframesConfig" do
      optional :feed, :message, 1, "airframes.AirframesClientFrame.AirframesConfig.Feed"
    end
    add_message "airframes.AirframesClientFrame.AirframesConfig.Feed" do
      optional :id, :string, 1
    end
  end
end

module Airframes
  AcarsdecMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("airframes.AcarsdecMessage").msgclass
  Vdlm2decMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("airframes.Vdlm2decMessage").msgclass
  TestRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("airframes.TestRequest").msgclass
  FrameRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("airframes.FrameRequest").msgclass
  AirframesClientFrame = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("airframes.AirframesClientFrame").msgclass
  AirframesClientFrame::Source = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("airframes.AirframesClientFrame.Source").msgclass
  AirframesClientFrame::Source::App = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("airframes.AirframesClientFrame.Source.App").msgclass
  AirframesClientFrame::Source::App::AppType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("airframes.AirframesClientFrame.Source.App.AppType").enummodule
  AirframesClientFrame::Source::Host = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("airframes.AirframesClientFrame.Source.Host").msgclass
  AirframesClientFrame::Source::Host::Platform = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("airframes.AirframesClientFrame.Source.Host.Platform").enummodule
  AirframesClientFrame::Source::Host::OperatingSystem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("airframes.AirframesClientFrame.Source.Host.OperatingSystem").enummodule
  AirframesClientFrame::Source::SourceType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("airframes.AirframesClientFrame.Source.SourceType").enummodule
  AirframesClientFrame::Source::SourceFormat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("airframes.AirframesClientFrame.Source.SourceFormat").enummodule
  AirframesClientFrame::AirframesConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("airframes.AirframesClientFrame.AirframesConfig").msgclass
  AirframesClientFrame::AirframesConfig::Feed = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("airframes.AirframesClientFrame.AirframesConfig.Feed").msgclass
end
