# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: airframes_client_output_frame.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("airframes_client_output_frame.proto", :syntax => :proto3) do
    add_message "AirframesClientOutputFrame" do
      optional :source, :message, 1, "AirframesClientOutputFrame.Source"
      optional :airframes, :message, 2, "AirframesClientOutputFrame.AirframesConfig"
      optional :payload, :string, 3
    end
    add_message "AirframesClientOutputFrame.Source" do
      optional :app, :message, 1, "AirframesClientOutputFrame.Source.App"
      optional :host, :message, 2, "AirframesClientOutputFrame.Source.Host"
      optional :type, :enum, 3, "AirframesClientOutputFrame.Source.SourceType"
      optional :format, :enum, 4, "AirframesClientOutputFrame.Source.SourceFormat"
    end
    add_message "AirframesClientOutputFrame.Source.App" do
      optional :type, :enum, 1, "AirframesClientOutputFrame.Source.App.AppType"
      optional :version, :string, 2
    end
    add_enum "AirframesClientOutputFrame.Source.App.AppType" do
      value :UNKNOWN_APP_TYPE, 0
      value :ACARSDEC, 1
      value :ACARSDECO2, 2
      value :VDLM2DEC, 3
      value :DUMPVDL2, 4
      value :JAERO, 5
      value :PC_HFDL, 6
      value :SORCERER, 7
    end
    add_message "AirframesClientOutputFrame.Source.Host" do
      optional :platform, :enum, 1, "AirframesClientOutputFrame.Source.Host.Platform"
      optional :os, :enum, 2, "AirframesClientOutputFrame.Source.Host.OperatingSystem"
      optional :version, :string, 3
    end
    add_enum "AirframesClientOutputFrame.Source.Host.Platform" do
      value :UNKNOWN_PLATFORM, 0
      value :X86_32, 1
      value :X86_64, 2
      value :ARM_V6, 3
      value :ARM_V7, 4
      value :ARM_64, 5
    end
    add_enum "AirframesClientOutputFrame.Source.Host.OperatingSystem" do
      value :UNKNOWN_OPERATING_SYSTEM, 0
      value :LINUX, 1
      value :MACOS, 2
      value :WINDOWS, 3
    end
    add_enum "AirframesClientOutputFrame.Source.SourceType" do
      value :ACARS, 0
      value :VDL, 1
      value :HFDL, 2
      value :AERO, 3
    end
    add_enum "AirframesClientOutputFrame.Source.SourceFormat" do
      value :HUMAN_READABLE_TEXT, 0
      value :BEAST, 1
      value :SBS3, 2
      value :PLANE_PLOTTER, 3
      value :JSON_GENERIC, 4
      value :JSON_ACARSDEC, 5
      value :JSON_VDLM2DEC, 6
    end
    add_message "AirframesClientOutputFrame.AirframesConfig" do
      optional :feed, :message, 1, "AirframesClientOutputFrame.AirframesConfig.Feed"
    end
    add_message "AirframesClientOutputFrame.AirframesConfig.Feed" do
      optional :id, :string, 1
    end
  end
end

AirframesClientOutputFrame = Google::Protobuf::DescriptorPool.generated_pool.lookup("AirframesClientOutputFrame").msgclass
AirframesClientOutputFrame::Source = Google::Protobuf::DescriptorPool.generated_pool.lookup("AirframesClientOutputFrame.Source").msgclass
AirframesClientOutputFrame::Source::App = Google::Protobuf::DescriptorPool.generated_pool.lookup("AirframesClientOutputFrame.Source.App").msgclass
AirframesClientOutputFrame::Source::App::AppType = Google::Protobuf::DescriptorPool.generated_pool.lookup("AirframesClientOutputFrame.Source.App.AppType").enummodule
AirframesClientOutputFrame::Source::Host = Google::Protobuf::DescriptorPool.generated_pool.lookup("AirframesClientOutputFrame.Source.Host").msgclass
AirframesClientOutputFrame::Source::Host::Platform = Google::Protobuf::DescriptorPool.generated_pool.lookup("AirframesClientOutputFrame.Source.Host.Platform").enummodule
AirframesClientOutputFrame::Source::Host::OperatingSystem = Google::Protobuf::DescriptorPool.generated_pool.lookup("AirframesClientOutputFrame.Source.Host.OperatingSystem").enummodule
AirframesClientOutputFrame::Source::SourceType = Google::Protobuf::DescriptorPool.generated_pool.lookup("AirframesClientOutputFrame.Source.SourceType").enummodule
AirframesClientOutputFrame::Source::SourceFormat = Google::Protobuf::DescriptorPool.generated_pool.lookup("AirframesClientOutputFrame.Source.SourceFormat").enummodule
AirframesClientOutputFrame::AirframesConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("AirframesClientOutputFrame.AirframesConfig").msgclass
AirframesClientOutputFrame::AirframesConfig::Feed = Google::Protobuf::DescriptorPool.generated_pool.lookup("AirframesClientOutputFrame.AirframesConfig.Feed").msgclass
