// source: airframes_client_frame.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.airframes.AirframesClientFrame');
goog.provide('proto.airframes.AirframesClientFrame.AirframesConfig');
goog.provide('proto.airframes.AirframesClientFrame.AirframesConfig.Feed');
goog.provide('proto.airframes.AirframesClientFrame.MessageCase');
goog.provide('proto.airframes.AirframesClientFrame.Source');
goog.provide('proto.airframes.AirframesClientFrame.Source.App');
goog.provide('proto.airframes.AirframesClientFrame.Source.App.AppType');
goog.provide('proto.airframes.AirframesClientFrame.Source.Host');
goog.provide('proto.airframes.AirframesClientFrame.Source.Host.OperatingSystem');
goog.provide('proto.airframes.AirframesClientFrame.Source.Host.Platform');
goog.provide('proto.airframes.AirframesClientFrame.Source.SourceFormat');
goog.provide('proto.airframes.AirframesClientFrame.Source.SourceType');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.airframes.AcarsdecMessage');
goog.require('proto.airframes.Vdlm2decMessage');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.airframes.AirframesClientFrame = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.airframes.AirframesClientFrame.oneofGroups_);
};
goog.inherits(proto.airframes.AirframesClientFrame, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.airframes.AirframesClientFrame.displayName = 'proto.airframes.AirframesClientFrame';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.airframes.AirframesClientFrame.Source = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.airframes.AirframesClientFrame.Source, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.airframes.AirframesClientFrame.Source.displayName = 'proto.airframes.AirframesClientFrame.Source';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.airframes.AirframesClientFrame.Source.App = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.airframes.AirframesClientFrame.Source.App, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.airframes.AirframesClientFrame.Source.App.displayName = 'proto.airframes.AirframesClientFrame.Source.App';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.airframes.AirframesClientFrame.Source.Host = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.airframes.AirframesClientFrame.Source.Host, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.airframes.AirframesClientFrame.Source.Host.displayName = 'proto.airframes.AirframesClientFrame.Source.Host';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.airframes.AirframesClientFrame.AirframesConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.airframes.AirframesClientFrame.AirframesConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.airframes.AirframesClientFrame.AirframesConfig.displayName = 'proto.airframes.AirframesClientFrame.AirframesConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.airframes.AirframesClientFrame.AirframesConfig.Feed = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.airframes.AirframesClientFrame.AirframesConfig.Feed, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.airframes.AirframesClientFrame.AirframesConfig.Feed.displayName = 'proto.airframes.AirframesClientFrame.AirframesConfig.Feed';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.airframes.AirframesClientFrame.oneofGroups_ = [[3,4]];

/**
 * @enum {number}
 */
proto.airframes.AirframesClientFrame.MessageCase = {
  MESSAGE_NOT_SET: 0,
  ACARSDEC_MESSAGE: 3,
  VDLM2DEC_MESSAGE: 4
};

/**
 * @return {proto.airframes.AirframesClientFrame.MessageCase}
 */
proto.airframes.AirframesClientFrame.prototype.getMessageCase = function() {
  return /** @type {proto.airframes.AirframesClientFrame.MessageCase} */(jspb.Message.computeOneofCase(this, proto.airframes.AirframesClientFrame.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.airframes.AirframesClientFrame.prototype.toObject = function(opt_includeInstance) {
  return proto.airframes.AirframesClientFrame.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.airframes.AirframesClientFrame} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airframes.AirframesClientFrame.toObject = function(includeInstance, msg) {
  var f, obj = {
    source: (f = msg.getSource()) && proto.airframes.AirframesClientFrame.Source.toObject(includeInstance, f),
    airframes: (f = msg.getAirframes()) && proto.airframes.AirframesClientFrame.AirframesConfig.toObject(includeInstance, f),
    acarsdecMessage: (f = msg.getAcarsdecMessage()) && proto.airframes.AcarsdecMessage.toObject(includeInstance, f),
    vdlm2decMessage: (f = msg.getVdlm2decMessage()) && proto.airframes.Vdlm2decMessage.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.airframes.AirframesClientFrame}
 */
proto.airframes.AirframesClientFrame.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.airframes.AirframesClientFrame;
  return proto.airframes.AirframesClientFrame.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.airframes.AirframesClientFrame} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.airframes.AirframesClientFrame}
 */
proto.airframes.AirframesClientFrame.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.airframes.AirframesClientFrame.Source;
      reader.readMessage(value,proto.airframes.AirframesClientFrame.Source.deserializeBinaryFromReader);
      msg.setSource(value);
      break;
    case 2:
      var value = new proto.airframes.AirframesClientFrame.AirframesConfig;
      reader.readMessage(value,proto.airframes.AirframesClientFrame.AirframesConfig.deserializeBinaryFromReader);
      msg.setAirframes(value);
      break;
    case 3:
      var value = new proto.airframes.AcarsdecMessage;
      reader.readMessage(value,proto.airframes.AcarsdecMessage.deserializeBinaryFromReader);
      msg.setAcarsdecMessage(value);
      break;
    case 4:
      var value = new proto.airframes.Vdlm2decMessage;
      reader.readMessage(value,proto.airframes.Vdlm2decMessage.deserializeBinaryFromReader);
      msg.setVdlm2decMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.airframes.AirframesClientFrame.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.airframes.AirframesClientFrame.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.airframes.AirframesClientFrame} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airframes.AirframesClientFrame.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSource();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.airframes.AirframesClientFrame.Source.serializeBinaryToWriter
    );
  }
  f = message.getAirframes();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.airframes.AirframesClientFrame.AirframesConfig.serializeBinaryToWriter
    );
  }
  f = message.getAcarsdecMessage();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.airframes.AcarsdecMessage.serializeBinaryToWriter
    );
  }
  f = message.getVdlm2decMessage();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.airframes.Vdlm2decMessage.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.airframes.AirframesClientFrame.Source.prototype.toObject = function(opt_includeInstance) {
  return proto.airframes.AirframesClientFrame.Source.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.airframes.AirframesClientFrame.Source} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airframes.AirframesClientFrame.Source.toObject = function(includeInstance, msg) {
  var f, obj = {
    app: (f = msg.getApp()) && proto.airframes.AirframesClientFrame.Source.App.toObject(includeInstance, f),
    host: (f = msg.getHost()) && proto.airframes.AirframesClientFrame.Source.Host.toObject(includeInstance, f),
    type: jspb.Message.getFieldWithDefault(msg, 3, 0),
    format: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.airframes.AirframesClientFrame.Source}
 */
proto.airframes.AirframesClientFrame.Source.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.airframes.AirframesClientFrame.Source;
  return proto.airframes.AirframesClientFrame.Source.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.airframes.AirframesClientFrame.Source} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.airframes.AirframesClientFrame.Source}
 */
proto.airframes.AirframesClientFrame.Source.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.airframes.AirframesClientFrame.Source.App;
      reader.readMessage(value,proto.airframes.AirframesClientFrame.Source.App.deserializeBinaryFromReader);
      msg.setApp(value);
      break;
    case 2:
      var value = new proto.airframes.AirframesClientFrame.Source.Host;
      reader.readMessage(value,proto.airframes.AirframesClientFrame.Source.Host.deserializeBinaryFromReader);
      msg.setHost(value);
      break;
    case 3:
      var value = /** @type {!proto.airframes.AirframesClientFrame.Source.SourceType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 4:
      var value = /** @type {!proto.airframes.AirframesClientFrame.Source.SourceFormat} */ (reader.readEnum());
      msg.setFormat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.airframes.AirframesClientFrame.Source.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.airframes.AirframesClientFrame.Source.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.airframes.AirframesClientFrame.Source} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airframes.AirframesClientFrame.Source.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getApp();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.airframes.AirframesClientFrame.Source.App.serializeBinaryToWriter
    );
  }
  f = message.getHost();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.airframes.AirframesClientFrame.Source.Host.serializeBinaryToWriter
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getFormat();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.airframes.AirframesClientFrame.Source.SourceType = {
  ACARS: 0,
  VDL: 1,
  HFDL: 2,
  AERO: 3
};

/**
 * @enum {number}
 */
proto.airframes.AirframesClientFrame.Source.SourceFormat = {
  HUMAN_READABLE_TEXT: 0,
  BEAST: 1,
  SBS3: 2,
  PLANE_PLOTTER: 3,
  JSON_GENERIC: 4,
  JSON_ACARSDEC: 5,
  JSON_VDLM2DEC: 6
};




if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.airframes.AirframesClientFrame.Source.App.prototype.toObject = function(opt_includeInstance) {
  return proto.airframes.AirframesClientFrame.Source.App.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.airframes.AirframesClientFrame.Source.App} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airframes.AirframesClientFrame.Source.App.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    version: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.airframes.AirframesClientFrame.Source.App}
 */
proto.airframes.AirframesClientFrame.Source.App.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.airframes.AirframesClientFrame.Source.App;
  return proto.airframes.AirframesClientFrame.Source.App.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.airframes.AirframesClientFrame.Source.App} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.airframes.AirframesClientFrame.Source.App}
 */
proto.airframes.AirframesClientFrame.Source.App.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.airframes.AirframesClientFrame.Source.App.AppType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.airframes.AirframesClientFrame.Source.App.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.airframes.AirframesClientFrame.Source.App.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.airframes.AirframesClientFrame.Source.App} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airframes.AirframesClientFrame.Source.App.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.airframes.AirframesClientFrame.Source.App.AppType = {
  UNKNOWN_APP_TYPE: 0,
  ACARSDEC: 1,
  ACARSDECO2: 2,
  VDLM2DEC: 3,
  DUMPVDL2: 4,
  JAERO: 5,
  PC_HFDL: 6,
  SORCERER: 7
};

/**
 * optional AppType type = 1;
 * @return {!proto.airframes.AirframesClientFrame.Source.App.AppType}
 */
proto.airframes.AirframesClientFrame.Source.App.prototype.getType = function() {
  return /** @type {!proto.airframes.AirframesClientFrame.Source.App.AppType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.airframes.AirframesClientFrame.Source.App.AppType} value
 * @return {!proto.airframes.AirframesClientFrame.Source.App} returns this
 */
proto.airframes.AirframesClientFrame.Source.App.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string version = 2;
 * @return {string}
 */
proto.airframes.AirframesClientFrame.Source.App.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.airframes.AirframesClientFrame.Source.App} returns this
 */
proto.airframes.AirframesClientFrame.Source.App.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.airframes.AirframesClientFrame.Source.Host.prototype.toObject = function(opt_includeInstance) {
  return proto.airframes.AirframesClientFrame.Source.Host.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.airframes.AirframesClientFrame.Source.Host} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airframes.AirframesClientFrame.Source.Host.toObject = function(includeInstance, msg) {
  var f, obj = {
    platform: jspb.Message.getFieldWithDefault(msg, 1, 0),
    os: jspb.Message.getFieldWithDefault(msg, 2, 0),
    version: jspb.Message.getFieldWithDefault(msg, 3, ""),
    nodeName: jspb.Message.getFieldWithDefault(msg, 4, ""),
    nodeIp: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.airframes.AirframesClientFrame.Source.Host}
 */
proto.airframes.AirframesClientFrame.Source.Host.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.airframes.AirframesClientFrame.Source.Host;
  return proto.airframes.AirframesClientFrame.Source.Host.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.airframes.AirframesClientFrame.Source.Host} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.airframes.AirframesClientFrame.Source.Host}
 */
proto.airframes.AirframesClientFrame.Source.Host.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.airframes.AirframesClientFrame.Source.Host.Platform} */ (reader.readEnum());
      msg.setPlatform(value);
      break;
    case 2:
      var value = /** @type {!proto.airframes.AirframesClientFrame.Source.Host.OperatingSystem} */ (reader.readEnum());
      msg.setOs(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setNodeName(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setNodeIp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.airframes.AirframesClientFrame.Source.Host.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.airframes.AirframesClientFrame.Source.Host.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.airframes.AirframesClientFrame.Source.Host} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airframes.AirframesClientFrame.Source.Host.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlatform();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getOs();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getNodeName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getNodeIp();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.airframes.AirframesClientFrame.Source.Host.Platform = {
  UNKNOWN_PLATFORM: 0,
  X86_32: 1,
  X86_64: 2,
  ARM_V6: 3,
  ARM_V7: 4,
  ARM_64: 5
};

/**
 * @enum {number}
 */
proto.airframes.AirframesClientFrame.Source.Host.OperatingSystem = {
  UNKNOWN_OPERATING_SYSTEM: 0,
  LINUX: 1,
  MACOS: 2,
  WINDOWS: 3
};

/**
 * optional Platform platform = 1;
 * @return {!proto.airframes.AirframesClientFrame.Source.Host.Platform}
 */
proto.airframes.AirframesClientFrame.Source.Host.prototype.getPlatform = function() {
  return /** @type {!proto.airframes.AirframesClientFrame.Source.Host.Platform} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.airframes.AirframesClientFrame.Source.Host.Platform} value
 * @return {!proto.airframes.AirframesClientFrame.Source.Host} returns this
 */
proto.airframes.AirframesClientFrame.Source.Host.prototype.setPlatform = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional OperatingSystem os = 2;
 * @return {!proto.airframes.AirframesClientFrame.Source.Host.OperatingSystem}
 */
proto.airframes.AirframesClientFrame.Source.Host.prototype.getOs = function() {
  return /** @type {!proto.airframes.AirframesClientFrame.Source.Host.OperatingSystem} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.airframes.AirframesClientFrame.Source.Host.OperatingSystem} value
 * @return {!proto.airframes.AirframesClientFrame.Source.Host} returns this
 */
proto.airframes.AirframesClientFrame.Source.Host.prototype.setOs = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string version = 3;
 * @return {string}
 */
proto.airframes.AirframesClientFrame.Source.Host.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.airframes.AirframesClientFrame.Source.Host} returns this
 */
proto.airframes.AirframesClientFrame.Source.Host.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string node_name = 4;
 * @return {string}
 */
proto.airframes.AirframesClientFrame.Source.Host.prototype.getNodeName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.airframes.AirframesClientFrame.Source.Host} returns this
 */
proto.airframes.AirframesClientFrame.Source.Host.prototype.setNodeName = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string node_ip = 5;
 * @return {string}
 */
proto.airframes.AirframesClientFrame.Source.Host.prototype.getNodeIp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.airframes.AirframesClientFrame.Source.Host} returns this
 */
proto.airframes.AirframesClientFrame.Source.Host.prototype.setNodeIp = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional App app = 1;
 * @return {?proto.airframes.AirframesClientFrame.Source.App}
 */
proto.airframes.AirframesClientFrame.Source.prototype.getApp = function() {
  return /** @type{?proto.airframes.AirframesClientFrame.Source.App} */ (
    jspb.Message.getWrapperField(this, proto.airframes.AirframesClientFrame.Source.App, 1));
};


/**
 * @param {?proto.airframes.AirframesClientFrame.Source.App|undefined} value
 * @return {!proto.airframes.AirframesClientFrame.Source} returns this
*/
proto.airframes.AirframesClientFrame.Source.prototype.setApp = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.airframes.AirframesClientFrame.Source} returns this
 */
proto.airframes.AirframesClientFrame.Source.prototype.clearApp = function() {
  return this.setApp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.airframes.AirframesClientFrame.Source.prototype.hasApp = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Host host = 2;
 * @return {?proto.airframes.AirframesClientFrame.Source.Host}
 */
proto.airframes.AirframesClientFrame.Source.prototype.getHost = function() {
  return /** @type{?proto.airframes.AirframesClientFrame.Source.Host} */ (
    jspb.Message.getWrapperField(this, proto.airframes.AirframesClientFrame.Source.Host, 2));
};


/**
 * @param {?proto.airframes.AirframesClientFrame.Source.Host|undefined} value
 * @return {!proto.airframes.AirframesClientFrame.Source} returns this
*/
proto.airframes.AirframesClientFrame.Source.prototype.setHost = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.airframes.AirframesClientFrame.Source} returns this
 */
proto.airframes.AirframesClientFrame.Source.prototype.clearHost = function() {
  return this.setHost(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.airframes.AirframesClientFrame.Source.prototype.hasHost = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional SourceType type = 3;
 * @return {!proto.airframes.AirframesClientFrame.Source.SourceType}
 */
proto.airframes.AirframesClientFrame.Source.prototype.getType = function() {
  return /** @type {!proto.airframes.AirframesClientFrame.Source.SourceType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.airframes.AirframesClientFrame.Source.SourceType} value
 * @return {!proto.airframes.AirframesClientFrame.Source} returns this
 */
proto.airframes.AirframesClientFrame.Source.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional SourceFormat format = 4;
 * @return {!proto.airframes.AirframesClientFrame.Source.SourceFormat}
 */
proto.airframes.AirframesClientFrame.Source.prototype.getFormat = function() {
  return /** @type {!proto.airframes.AirframesClientFrame.Source.SourceFormat} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.airframes.AirframesClientFrame.Source.SourceFormat} value
 * @return {!proto.airframes.AirframesClientFrame.Source} returns this
 */
proto.airframes.AirframesClientFrame.Source.prototype.setFormat = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.airframes.AirframesClientFrame.AirframesConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.airframes.AirframesClientFrame.AirframesConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.airframes.AirframesClientFrame.AirframesConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airframes.AirframesClientFrame.AirframesConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    feed: (f = msg.getFeed()) && proto.airframes.AirframesClientFrame.AirframesConfig.Feed.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.airframes.AirframesClientFrame.AirframesConfig}
 */
proto.airframes.AirframesClientFrame.AirframesConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.airframes.AirframesClientFrame.AirframesConfig;
  return proto.airframes.AirframesClientFrame.AirframesConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.airframes.AirframesClientFrame.AirframesConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.airframes.AirframesClientFrame.AirframesConfig}
 */
proto.airframes.AirframesClientFrame.AirframesConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.airframes.AirframesClientFrame.AirframesConfig.Feed;
      reader.readMessage(value,proto.airframes.AirframesClientFrame.AirframesConfig.Feed.deserializeBinaryFromReader);
      msg.setFeed(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.airframes.AirframesClientFrame.AirframesConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.airframes.AirframesClientFrame.AirframesConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.airframes.AirframesClientFrame.AirframesConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airframes.AirframesClientFrame.AirframesConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFeed();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.airframes.AirframesClientFrame.AirframesConfig.Feed.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.airframes.AirframesClientFrame.AirframesConfig.Feed.prototype.toObject = function(opt_includeInstance) {
  return proto.airframes.AirframesClientFrame.AirframesConfig.Feed.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.airframes.AirframesClientFrame.AirframesConfig.Feed} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airframes.AirframesClientFrame.AirframesConfig.Feed.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.airframes.AirframesClientFrame.AirframesConfig.Feed}
 */
proto.airframes.AirframesClientFrame.AirframesConfig.Feed.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.airframes.AirframesClientFrame.AirframesConfig.Feed;
  return proto.airframes.AirframesClientFrame.AirframesConfig.Feed.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.airframes.AirframesClientFrame.AirframesConfig.Feed} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.airframes.AirframesClientFrame.AirframesConfig.Feed}
 */
proto.airframes.AirframesClientFrame.AirframesConfig.Feed.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.airframes.AirframesClientFrame.AirframesConfig.Feed.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.airframes.AirframesClientFrame.AirframesConfig.Feed.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.airframes.AirframesClientFrame.AirframesConfig.Feed} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airframes.AirframesClientFrame.AirframesConfig.Feed.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.airframes.AirframesClientFrame.AirframesConfig.Feed.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.airframes.AirframesClientFrame.AirframesConfig.Feed} returns this
 */
proto.airframes.AirframesClientFrame.AirframesConfig.Feed.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Feed feed = 1;
 * @return {?proto.airframes.AirframesClientFrame.AirframesConfig.Feed}
 */
proto.airframes.AirframesClientFrame.AirframesConfig.prototype.getFeed = function() {
  return /** @type{?proto.airframes.AirframesClientFrame.AirframesConfig.Feed} */ (
    jspb.Message.getWrapperField(this, proto.airframes.AirframesClientFrame.AirframesConfig.Feed, 1));
};


/**
 * @param {?proto.airframes.AirframesClientFrame.AirframesConfig.Feed|undefined} value
 * @return {!proto.airframes.AirframesClientFrame.AirframesConfig} returns this
*/
proto.airframes.AirframesClientFrame.AirframesConfig.prototype.setFeed = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.airframes.AirframesClientFrame.AirframesConfig} returns this
 */
proto.airframes.AirframesClientFrame.AirframesConfig.prototype.clearFeed = function() {
  return this.setFeed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.airframes.AirframesClientFrame.AirframesConfig.prototype.hasFeed = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Source source = 1;
 * @return {?proto.airframes.AirframesClientFrame.Source}
 */
proto.airframes.AirframesClientFrame.prototype.getSource = function() {
  return /** @type{?proto.airframes.AirframesClientFrame.Source} */ (
    jspb.Message.getWrapperField(this, proto.airframes.AirframesClientFrame.Source, 1));
};


/**
 * @param {?proto.airframes.AirframesClientFrame.Source|undefined} value
 * @return {!proto.airframes.AirframesClientFrame} returns this
*/
proto.airframes.AirframesClientFrame.prototype.setSource = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.airframes.AirframesClientFrame} returns this
 */
proto.airframes.AirframesClientFrame.prototype.clearSource = function() {
  return this.setSource(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.airframes.AirframesClientFrame.prototype.hasSource = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional AirframesConfig airframes = 2;
 * @return {?proto.airframes.AirframesClientFrame.AirframesConfig}
 */
proto.airframes.AirframesClientFrame.prototype.getAirframes = function() {
  return /** @type{?proto.airframes.AirframesClientFrame.AirframesConfig} */ (
    jspb.Message.getWrapperField(this, proto.airframes.AirframesClientFrame.AirframesConfig, 2));
};


/**
 * @param {?proto.airframes.AirframesClientFrame.AirframesConfig|undefined} value
 * @return {!proto.airframes.AirframesClientFrame} returns this
*/
proto.airframes.AirframesClientFrame.prototype.setAirframes = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.airframes.AirframesClientFrame} returns this
 */
proto.airframes.AirframesClientFrame.prototype.clearAirframes = function() {
  return this.setAirframes(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.airframes.AirframesClientFrame.prototype.hasAirframes = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional AcarsdecMessage acarsdec_message = 3;
 * @return {?proto.airframes.AcarsdecMessage}
 */
proto.airframes.AirframesClientFrame.prototype.getAcarsdecMessage = function() {
  return /** @type{?proto.airframes.AcarsdecMessage} */ (
    jspb.Message.getWrapperField(this, proto.airframes.AcarsdecMessage, 3));
};


/**
 * @param {?proto.airframes.AcarsdecMessage|undefined} value
 * @return {!proto.airframes.AirframesClientFrame} returns this
*/
proto.airframes.AirframesClientFrame.prototype.setAcarsdecMessage = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.airframes.AirframesClientFrame.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.airframes.AirframesClientFrame} returns this
 */
proto.airframes.AirframesClientFrame.prototype.clearAcarsdecMessage = function() {
  return this.setAcarsdecMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.airframes.AirframesClientFrame.prototype.hasAcarsdecMessage = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Vdlm2decMessage vdlm2dec_message = 4;
 * @return {?proto.airframes.Vdlm2decMessage}
 */
proto.airframes.AirframesClientFrame.prototype.getVdlm2decMessage = function() {
  return /** @type{?proto.airframes.Vdlm2decMessage} */ (
    jspb.Message.getWrapperField(this, proto.airframes.Vdlm2decMessage, 4));
};


/**
 * @param {?proto.airframes.Vdlm2decMessage|undefined} value
 * @return {!proto.airframes.AirframesClientFrame} returns this
*/
proto.airframes.AirframesClientFrame.prototype.setVdlm2decMessage = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.airframes.AirframesClientFrame.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.airframes.AirframesClientFrame} returns this
 */
proto.airframes.AirframesClientFrame.prototype.clearVdlm2decMessage = function() {
  return this.setVdlm2decMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.airframes.AirframesClientFrame.prototype.hasVdlm2decMessage = function() {
  return jspb.Message.getField(this, 4) != null;
};


